version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: peterson
      POSTGRES_PASSWORD: test
    ports:
      - 5432

  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b 0.0.0.0"
    command: bash -c "rm -f tmp/pids/server.pid && rdebug-ide --host 0.0.0.0 --port 8999 -- bin/rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'petersondaronch@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'bumblebee'
      PGADMIN_LISTEN_PORT: '8080'
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  gems:
